// <auto-generated />
using Carona_Service.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Carona_Service.Migrations
{
    [DbContext(typeof(Carona_ServiceContext))]
    [Migration("20171130025026_TesteGeography")]
    partial class TesteGeography
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Carona_Service.Models.CaronaBusca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<DateTime>("HorarioChegada");

                    b.Property<DateTime>("HorarioPartida");

                    b.Property<Guid>("IdUsuario");

                    b.HasKey("Id");

                    b.ToTable("CaronaBusca");
                });

            modelBuilder.Entity("Carona_Service.Models.CaronaOferta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<DateTime>("HorarioChegada");

                    b.Property<DateTime>("HorarioPartida");

                    b.Property<Guid>("IdUsuario");

                    b.HasKey("Id");

                    b.ToTable("CaronaOferta");
                });

            modelBuilder.Entity("Carona_Service.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cpf")
                        .HasMaxLength(11);

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<string>("Telefone");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Carona_Service.Models.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cor");

                    b.Property<Guid>("IdUsuario");

                    b.Property<string>("Modelo");

                    b.Property<string>("Placa");

                    b.HasKey("Id");

                    b.ToTable("Veiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
