// <auto-generated />
using Carona_Service.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Carona_Service.Migrations
{
    [DbContext(typeof(Carona_ServiceContext))]
    [Migration("20171119150215_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Carona_Service.Models.Carona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<DateTime>("HorarioChegada");

                    b.Property<Guid>("IdUsuario");

                    b.Property<string>("PontoChegada");

                    b.Property<string>("PontoPartida");

                    b.Property<string>("PontosIntermediarios");

                    b.HasKey("Id");

                    b.ToTable("Carona");
                });
#pragma warning restore 612, 618
        }
    }
}
